# -*- coding: utf-8 -*-
"""workshopPYPD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7YeZC9zz3A4DlV2PtglLOeMzGCNZxx7

#Workshop Python com Pandas
"""

import pandas as pd

dataframe = pd.read_csv('aluguel.csv', delimiter = ';')

dataframe.head()

dataframe.dtypes

dataframe.shape

dataframe.describe()

"""#Séries e Dataframes"""

dataframe['Bairro']

type(dataframe['Bairro'])

type(dataframe)

serie_bairro = dataframe['Tipo']
serie_bairro

tipo_imovel = pd.DataFrame(dataframe['Tipo'])
tipo_imovel.head()

tipo_imovel.drop_duplicates(inplace=True)
tipo_imovel

tipo_imovel.index

tipo_imovel.reset_index(inplace=True, drop=True)
tipo_imovel

dataframe[dataframe["Tipo"] == "Casa"].head()

tipo_imovel

residenciais = ['Quitinete',
                'Casa',
                'Apartamento',
                'Casa de Condomínio',
                'Casa de Vila']

imoveis_residenciais = dataframe[dataframe["Tipo"]
                                 .isin(residenciais)]
imoveis_residenciais.shape[0], dataframe.shape[0]

"""#Salvar um .csv"""

imoveis_residenciais.to_csv('imoveis_residenciais.csv',
                            index=False)

imoveis_residenciais = pd.read_csv('imoveis_residenciais.csv')
imoveis_residenciais

"""#Mais seleções"""

selecao = ((imoveis_residenciais['Tipo'] == 'Apartamento') & 
           (imoveis_residenciais['Bairro'] == 'Copacabana'))
imoveis_residenciais[selecao].head()

dataframe.info()

dataframe[dataframe['Valor'].isnull()]

dataframe.dropna(subset=['Valor'], inplace=True)

dataframe[dataframe['Valor'].isnull()]

selecao = ((dataframe['Tipo'] == "Apartamento") &
           (dataframe['Condominio'].isnull()))
dados_tratados = (dataframe[selecao]
                    .fillna({'Condominio':0, 'IPTU':0}))
dados_tratados.head(10)

dados_tratados['Valor Bruto'] =(dados_tratados['Condominio'] +
                                dados_tratados['Valor'] +
                                dados_tratados['IPTU'])
dados_tratados.head(10)

bairro = ['Copacabana', 
          'Ipanema', 
          'Leblon',
          'Tijuca']

selecao = dados_tratados['Bairro'].isin(bairro)

dados = dados_tratados[selecao]
dados.head(3)

grupo_bairro = dados.groupby('Bairro')

import matplotlib.pyplot as plt

plt.rc('figure', figsize=(8,6))

fig = grupo_bairro['Valor'].mean().plot.bar(color='blue')

